// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/java/org/example/proto/message.proto
// Protobuf Java Version: 4.28.3

package org.example.proto.tutorial;

public interface KafkaMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.KafkaMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>.tutorial.KafkaMessage.RequestType request_type = 2;</code>
   * @return The enum numeric value on the wire for requestType.
   */
  int getRequestTypeValue();
  /**
   * <code>.tutorial.KafkaMessage.RequestType request_type = 2;</code>
   * @return The requestType.
   */
  KafkaMessage.RequestType getRequestType();

  /**
   * <code>.tutorial.KafkaMessage.MethodType methos_type = 3;</code>
   * @return The enum numeric value on the wire for methosType.
   */
  int getMethosTypeValue();
  /**
   * <code>.tutorial.KafkaMessage.MethodType methos_type = 3;</code>
   * @return The methosType.
   */
  KafkaMessage.MethodType getMethosType();

  /**
   * <code>string body = 4;</code>
   * @return The body.
   */
  java.lang.String getBody();
  /**
   * <code>string body = 4;</code>
   * @return The bytes for body.
   */
  com.google.protobuf.ByteString
      getBodyBytes();

  /**
   * <code>string reply_to = 5;</code>
   * @return The replyTo.
   */
  java.lang.String getReplyTo();
  /**
   * <code>string reply_to = 5;</code>
   * @return The bytes for replyTo.
   */
  com.google.protobuf.ByteString
      getReplyToBytes();
}
