// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/java/org/example/kafka/proto/message.proto
// Protobuf Java Version: 4.28.3

package org.example.kafka.proto.tutorial;

/**
 * Protobuf type {@code tutorial.KafkaMessage}
 */
public final class KafkaMessage extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:tutorial.KafkaMessage)
    KafkaMessageOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      KafkaMessage.class.getName());
  }
  // Use KafkaMessage.newBuilder() to construct.
  private KafkaMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private KafkaMessage() {
    correlationId_ = "";
    requestType_ = 0;
    requestResult_ = 0;
    body_ = "";
    replyTo_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return KafkaMessageSample.internal_static_tutorial_KafkaMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return KafkaMessageSample.internal_static_tutorial_KafkaMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            KafkaMessage.class, KafkaMessage.Builder.class);
  }

  /**
   * Protobuf enum {@code tutorial.KafkaMessage.RequestResult}
   */
  public enum RequestResult
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>FAILED = 0;</code>
     */
    FAILED(0),
    /**
     * <code>SUCCESS = 1;</code>
     */
    SUCCESS(1),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 3,
        /* suffix= */ "",
        RequestResult.class.getName());
    }
    /**
     * <code>FAILED = 0;</code>
     */
    public static final int FAILED_VALUE = 0;
    /**
     * <code>SUCCESS = 1;</code>
     */
    public static final int SUCCESS_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RequestResult valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static RequestResult forNumber(int value) {
      switch (value) {
        case 0: return FAILED;
        case 1: return SUCCESS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RequestResult>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RequestResult> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RequestResult>() {
            public RequestResult findValueByNumber(int number) {
              return RequestResult.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return KafkaMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final RequestResult[] VALUES = values();

    public static RequestResult valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RequestResult(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:tutorial.KafkaMessage.RequestResult)
  }

  /**
   * Protobuf enum {@code tutorial.KafkaMessage.RequestType}
   */
  public enum RequestType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>RESPONSE = 0;</code>
     */
    RESPONSE(0),
    /**
     * <code>NOTIFY = 1;</code>
     */
    NOTIFY(1),
    /**
     * <code>REQUEST = 3;</code>
     */
    REQUEST(3),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 3,
        /* suffix= */ "",
        RequestType.class.getName());
    }
    /**
     * <code>RESPONSE = 0;</code>
     */
    public static final int RESPONSE_VALUE = 0;
    /**
     * <code>NOTIFY = 1;</code>
     */
    public static final int NOTIFY_VALUE = 1;
    /**
     * <code>REQUEST = 3;</code>
     */
    public static final int REQUEST_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RequestType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static RequestType forNumber(int value) {
      switch (value) {
        case 0: return RESPONSE;
        case 1: return NOTIFY;
        case 3: return REQUEST;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RequestType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
            public RequestType findValueByNumber(int number) {
              return RequestType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return KafkaMessage.getDescriptor().getEnumTypes().get(1);
    }

    private static final RequestType[] VALUES = values();

    public static RequestType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RequestType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:tutorial.KafkaMessage.RequestType)
  }

  public static final int CORRELATIONID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object correlationId_ = "";
  /**
   * <code>string correlationId = 1;</code>
   * @return The correlationId.
   */
  @java.lang.Override
  public java.lang.String getCorrelationId() {
    java.lang.Object ref = correlationId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      correlationId_ = s;
      return s;
    }
  }
  /**
   * <code>string correlationId = 1;</code>
   * @return The bytes for correlationId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCorrelationIdBytes() {
    java.lang.Object ref = correlationId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      correlationId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REQUESTTYPE_FIELD_NUMBER = 2;
  private int requestType_ = 0;
  /**
   * <code>.tutorial.KafkaMessage.RequestType requestType = 2;</code>
   * @return The enum numeric value on the wire for requestType.
   */
  @java.lang.Override public int getRequestTypeValue() {
    return requestType_;
  }
  /**
   * <code>.tutorial.KafkaMessage.RequestType requestType = 2;</code>
   * @return The requestType.
   */
  @java.lang.Override public KafkaMessage.RequestType getRequestType() {
    KafkaMessage.RequestType result = KafkaMessage.RequestType.forNumber(requestType_);
    return result == null ? KafkaMessage.RequestType.UNRECOGNIZED : result;
  }

  public static final int REQUESTRESULT_FIELD_NUMBER = 3;
  private int requestResult_ = 0;
  /**
   * <code>.tutorial.KafkaMessage.RequestResult requestResult = 3;</code>
   * @return The enum numeric value on the wire for requestResult.
   */
  @java.lang.Override public int getRequestResultValue() {
    return requestResult_;
  }
  /**
   * <code>.tutorial.KafkaMessage.RequestResult requestResult = 3;</code>
   * @return The requestResult.
   */
  @java.lang.Override public KafkaMessage.RequestResult getRequestResult() {
    KafkaMessage.RequestResult result = KafkaMessage.RequestResult.forNumber(requestResult_);
    return result == null ? KafkaMessage.RequestResult.UNRECOGNIZED : result;
  }

  public static final int BODY_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object body_ = "";
  /**
   * <code>string body = 4;</code>
   * @return The body.
   */
  @java.lang.Override
  public java.lang.String getBody() {
    java.lang.Object ref = body_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      body_ = s;
      return s;
    }
  }
  /**
   * <code>string body = 4;</code>
   * @return The bytes for body.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBodyBytes() {
    java.lang.Object ref = body_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      body_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REPLY_TO_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object replyTo_ = "";
  /**
   * <code>string reply_to = 5;</code>
   * @return The replyTo.
   */
  @java.lang.Override
  public java.lang.String getReplyTo() {
    java.lang.Object ref = replyTo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      replyTo_ = s;
      return s;
    }
  }
  /**
   * <code>string reply_to = 5;</code>
   * @return The bytes for replyTo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReplyToBytes() {
    java.lang.Object ref = replyTo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      replyTo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(correlationId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, correlationId_);
    }
    if (requestType_ != KafkaMessage.RequestType.RESPONSE.getNumber()) {
      output.writeEnum(2, requestType_);
    }
    if (requestResult_ != KafkaMessage.RequestResult.FAILED.getNumber()) {
      output.writeEnum(3, requestResult_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(body_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, body_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(replyTo_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, replyTo_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(correlationId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, correlationId_);
    }
    if (requestType_ != KafkaMessage.RequestType.RESPONSE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, requestType_);
    }
    if (requestResult_ != KafkaMessage.RequestResult.FAILED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, requestResult_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(body_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, body_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(replyTo_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, replyTo_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof KafkaMessage)) {
      return super.equals(obj);
    }
    KafkaMessage other = (KafkaMessage) obj;

    if (!getCorrelationId()
        .equals(other.getCorrelationId())) return false;
    if (requestType_ != other.requestType_) return false;
    if (requestResult_ != other.requestResult_) return false;
    if (!getBody()
        .equals(other.getBody())) return false;
    if (!getReplyTo()
        .equals(other.getReplyTo())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CORRELATIONID_FIELD_NUMBER;
    hash = (53 * hash) + getCorrelationId().hashCode();
    hash = (37 * hash) + REQUESTTYPE_FIELD_NUMBER;
    hash = (53 * hash) + requestType_;
    hash = (37 * hash) + REQUESTRESULT_FIELD_NUMBER;
    hash = (53 * hash) + requestResult_;
    hash = (37 * hash) + BODY_FIELD_NUMBER;
    hash = (53 * hash) + getBody().hashCode();
    hash = (37 * hash) + REPLY_TO_FIELD_NUMBER;
    hash = (53 * hash) + getReplyTo().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static KafkaMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static KafkaMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static KafkaMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static KafkaMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static KafkaMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static KafkaMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static KafkaMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static KafkaMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static KafkaMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static KafkaMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static KafkaMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static KafkaMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(KafkaMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tutorial.KafkaMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tutorial.KafkaMessage)
          KafkaMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return KafkaMessageSample.internal_static_tutorial_KafkaMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return KafkaMessageSample.internal_static_tutorial_KafkaMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              KafkaMessage.class, KafkaMessage.Builder.class);
    }

    // Construct using tutorial.KafkaMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      correlationId_ = "";
      requestType_ = 0;
      requestResult_ = 0;
      body_ = "";
      replyTo_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return KafkaMessageSample.internal_static_tutorial_KafkaMessage_descriptor;
    }

    @java.lang.Override
    public KafkaMessage getDefaultInstanceForType() {
      return KafkaMessage.getDefaultInstance();
    }

    @java.lang.Override
    public KafkaMessage build() {
      KafkaMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public KafkaMessage buildPartial() {
      KafkaMessage result = new KafkaMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(KafkaMessage result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.correlationId_ = correlationId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.requestType_ = requestType_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.requestResult_ = requestResult_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.body_ = body_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.replyTo_ = replyTo_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof KafkaMessage) {
        return mergeFrom((KafkaMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(KafkaMessage other) {
      if (other == KafkaMessage.getDefaultInstance()) return this;
      if (!other.getCorrelationId().isEmpty()) {
        correlationId_ = other.correlationId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.requestType_ != 0) {
        setRequestTypeValue(other.getRequestTypeValue());
      }
      if (other.requestResult_ != 0) {
        setRequestResultValue(other.getRequestResultValue());
      }
      if (!other.getBody().isEmpty()) {
        body_ = other.body_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getReplyTo().isEmpty()) {
        replyTo_ = other.replyTo_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              correlationId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              requestType_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              requestResult_ = input.readEnum();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              body_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              replyTo_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object correlationId_ = "";
    /**
     * <code>string correlationId = 1;</code>
     * @return The correlationId.
     */
    public java.lang.String getCorrelationId() {
      java.lang.Object ref = correlationId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        correlationId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string correlationId = 1;</code>
     * @return The bytes for correlationId.
     */
    public com.google.protobuf.ByteString
        getCorrelationIdBytes() {
      java.lang.Object ref = correlationId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        correlationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string correlationId = 1;</code>
     * @param value The correlationId to set.
     * @return This builder for chaining.
     */
    public Builder setCorrelationId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      correlationId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string correlationId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCorrelationId() {
      correlationId_ = getDefaultInstance().getCorrelationId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string correlationId = 1;</code>
     * @param value The bytes for correlationId to set.
     * @return This builder for chaining.
     */
    public Builder setCorrelationIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      correlationId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int requestType_ = 0;
    /**
     * <code>.tutorial.KafkaMessage.RequestType requestType = 2;</code>
     * @return The enum numeric value on the wire for requestType.
     */
    @java.lang.Override public int getRequestTypeValue() {
      return requestType_;
    }
    /**
     * <code>.tutorial.KafkaMessage.RequestType requestType = 2;</code>
     * @param value The enum numeric value on the wire for requestType to set.
     * @return This builder for chaining.
     */
    public Builder setRequestTypeValue(int value) {
      requestType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.tutorial.KafkaMessage.RequestType requestType = 2;</code>
     * @return The requestType.
     */
    @java.lang.Override
    public KafkaMessage.RequestType getRequestType() {
      KafkaMessage.RequestType result = KafkaMessage.RequestType.forNumber(requestType_);
      return result == null ? KafkaMessage.RequestType.UNRECOGNIZED : result;
    }
    /**
     * <code>.tutorial.KafkaMessage.RequestType requestType = 2;</code>
     * @param value The requestType to set.
     * @return This builder for chaining.
     */
    public Builder setRequestType(KafkaMessage.RequestType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      requestType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.tutorial.KafkaMessage.RequestType requestType = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      requestType_ = 0;
      onChanged();
      return this;
    }

    private int requestResult_ = 0;
    /**
     * <code>.tutorial.KafkaMessage.RequestResult requestResult = 3;</code>
     * @return The enum numeric value on the wire for requestResult.
     */
    @java.lang.Override public int getRequestResultValue() {
      return requestResult_;
    }
    /**
     * <code>.tutorial.KafkaMessage.RequestResult requestResult = 3;</code>
     * @param value The enum numeric value on the wire for requestResult to set.
     * @return This builder for chaining.
     */
    public Builder setRequestResultValue(int value) {
      requestResult_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.tutorial.KafkaMessage.RequestResult requestResult = 3;</code>
     * @return The requestResult.
     */
    @java.lang.Override
    public KafkaMessage.RequestResult getRequestResult() {
      KafkaMessage.RequestResult result = KafkaMessage.RequestResult.forNumber(requestResult_);
      return result == null ? KafkaMessage.RequestResult.UNRECOGNIZED : result;
    }
    /**
     * <code>.tutorial.KafkaMessage.RequestResult requestResult = 3;</code>
     * @param value The requestResult to set.
     * @return This builder for chaining.
     */
    public Builder setRequestResult(KafkaMessage.RequestResult value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      requestResult_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.tutorial.KafkaMessage.RequestResult requestResult = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestResult() {
      bitField0_ = (bitField0_ & ~0x00000004);
      requestResult_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object body_ = "";
    /**
     * <code>string body = 4;</code>
     * @return The body.
     */
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        body_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string body = 4;</code>
     * @return The bytes for body.
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string body = 4;</code>
     * @param value The body to set.
     * @return This builder for chaining.
     */
    public Builder setBody(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      body_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string body = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearBody() {
      body_ = getDefaultInstance().getBody();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string body = 4;</code>
     * @param value The bytes for body to set.
     * @return This builder for chaining.
     */
    public Builder setBodyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      body_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object replyTo_ = "";
    /**
     * <code>string reply_to = 5;</code>
     * @return The replyTo.
     */
    public java.lang.String getReplyTo() {
      java.lang.Object ref = replyTo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        replyTo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string reply_to = 5;</code>
     * @return The bytes for replyTo.
     */
    public com.google.protobuf.ByteString
        getReplyToBytes() {
      java.lang.Object ref = replyTo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        replyTo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string reply_to = 5;</code>
     * @param value The replyTo to set.
     * @return This builder for chaining.
     */
    public Builder setReplyTo(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      replyTo_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string reply_to = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearReplyTo() {
      replyTo_ = getDefaultInstance().getReplyTo();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string reply_to = 5;</code>
     * @param value The bytes for replyTo to set.
     * @return This builder for chaining.
     */
    public Builder setReplyToBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      replyTo_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:tutorial.KafkaMessage)
  }

  // @@protoc_insertion_point(class_scope:tutorial.KafkaMessage)
  private static final KafkaMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new KafkaMessage();
  }

  public static KafkaMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<KafkaMessage>
      PARSER = new com.google.protobuf.AbstractParser<KafkaMessage>() {
    @java.lang.Override
    public KafkaMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<KafkaMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<KafkaMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public KafkaMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

