spring:
  datasource:
    url: jdbc:h2:file:./data/demo
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

logging:
  level:
    root: INFO               # Уровень логирования для корневого логгера
    org.hibernate.SQL: DEBUG  # Логирование SQL-запросов
    org.hibernate.type: TRACE  # Логирование типов данных
    # Добавьте дополнительные пакеты по мере необходимости
server:
  port: 8080
