spring:
  profiles:
    active: withoutKafka
  datasource:
    url: jdbc:postgresql://localhost:5432/croud_invest_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: withKafka
kafka:
  bootstrap-servers: localhost:9092
  consumer:
    auto-offset-reset: earliest
    enable-auto-commit: true
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

---
spring:
  config:
    activate:
      on-profile: withoutKafka
kafka:
  bootstrap-servers: ""
  consumer: {}
  producer: {}
